### ISSUE TITLE
Suggestion on new feature "Color Conversion Preset"

### ISSUE THREAD

**Issue by Real-Moomin** [eddiesigner/sketch-dark-mode#16]
Also, I have suggestion for your plug in.

I suggest you a new feature "Color Conversion Preset"

Once I convert light theme to dark theme, It works very well.
But every time I open other sketch files and try to convert colors, I have to do same task.
![image](https://user-images.githubusercontent.com/26920609/97953802-ecf28d80-1de4-11eb-9ba3-3dcfbaf3182b.png)

(For example, I have to type in "#ffaaaa" and "65aaaa" for every single project.)

Here's a prototype I made.
Once I save preset, I can reuse them whenever I want :)

![image](https://user-images.githubusercontent.com/26920609/97954144-0ba55400-1de6-11eb-9c27-3fa7fb1694f5.png)

Please consider as a new feature :)

Thank you so much.
😊

**Comment by eddiesigner** [comment]
While this functionality could be useful, I think for now is something specific to your case, also remember that you still have the option of creating a Library where you add color variables which you could use in your other documents.

This functionality would take some time and for now I don't see it as necessary since you can "replicate" it relatively easily by creating a Library. Maybe in the future I will implement something similar but not for now, so thanks for the suggestion!
