### ISSUE TITLE
Saved Library Palette doesn't save across different Sketch documents

### ISSUE THREAD

**Issue by aCassi** [eddiesigner/sketch-dark-mode#20]
Hi :)
I saved a library color palette in the plugin modal, but this palette is available only in the current document. Once I open a new Sketch document I got the library palette empty and I need to fill it again.
Is there a way to avoid filling the palette each time I change Sketch document?

Thanks,
Andrea

**Comment by eddiesigner** [comment]
Hi,

This plugin saves the color palette per document, that's why it's not available in different documents. If you want to use the same color palette across documents you can create a [Library](https://www.sketch.com/docs/libraries/) and save it there (don't forget to save that file), then in any of your documents you can open the plugin and press the gear button to use Library colors, you will see a list where you can select the Library you just created and start using their colors.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
