### ISSUE TITLE
Dark mode detach library symbols

### ISSUE THREAD

**Issue by aCassi** [eddiesigner/sketch-dark-mode#21]
Hi, it's me again :D
is there a way to stop the detachment of library symbols when you switch to dark mode?

Thanks,
Andrea

**Comment by eddiesigner** [comment]
Not really, the plugin detaches symbols in order to recreate them using the dark mode colors. Maybe you're asking that because you want to keep symbols in dark mode? If you want to have symbols in dark mode so you can use them later on you can create a Symbol Page with all your regular symbols and then  [generate a dark mode version of that Page](https://github.com/eddiesigner/sketch-dark-mode/wiki/How-to-use-Sketch-Dark-Mode#generate-the-dark-mode-version-of-your-current-page), by doing that you will have all your symbols in dark mode available for later use.

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
