### ISSUE TITLE
Not Work in 70.6

### ISSUE THREAD

**Issue by yangbe** [eddiesigner/sketch-dark-mode#24]
## 1、It doesn‘t change to the Dark Mode，even I make the setting according to the guide

![image](https://user-images.githubusercontent.com/9880101/110228070-27a63700-7f39-11eb-8a8e-14f03463fd30.png)

---

## 2、The library Palette setting will be cleared once I open/create a new document, and I have to set the color HEX value  again and again. 

![image](https://user-images.githubusercontent.com/9880101/110228036-e0b84180-7f38-11eb-88d9-727cad57fd92.png)

**Comment by yangbe** [comment]
https://github.com/receptiryaki/darkside

Here is another way to manage the color palette. What I hope is that setting the Light and Dark color in one place, and can be used in anywhere.

**Comment by eddiesigner** [comment]
Are you sure that the layers of your document are using those color variables? 
https://github.com/eddiesigner/sketch-dark-mode/wiki/How-to-use-Sketch-Dark-Mode#2-use-your-colors-in-the-layers-of-your-document

![](https://res.cloudinary.com/edev/image/upload/v1587293216/sketch-dark-mode/Screenshot_2020-04-19_at_12.45.38.png)

I tested it on Sketch 70.6 and it works just fine.

You have to save your document in order to persist the color palette. If you want to reuse the same color palette across documents you can create a Library document and save the colors there (don't forget to save that file), then you can click the gear button to choose the Library you just created to use it in other documents.

**Comment by yangbe** [comment]
Absolutely sure!!  It works well when I choose color variables from [this document] , and it doesn't when choose from my color library named [color_palette].


![image](https://user-images.githubusercontent.com/9880101/110348311-79031300-806c-11eb-9aa0-2f4d2bbc137a.png)

**Comment by eddiesigner** [comment]
I see, it seems like could be the same issue already discussed here: https://github.com/eddiesigner/sketch-dark-mode/issues/19

> Did you save your library file before open the plugin window? If you library comes from the cloud, you might need to update it before opening the plugin.
