### ISSUE TITLE
Transparency support

### ISSUE THREAD

**Issue by PeakXing** [eddiesigner/sketch-dark-mode#6]
The plugin is very useful, it would be perfect if it can support transparency.

**Comment by eddiesigner** [comment]
This plugin relies on [Color Assets](https://developer.sketch.com/reference/api/#color-asset) which use hexadecimal colors, so in the foreseeable future that won't be an option.

You can handle opacity easily with Sketch if you need it, also you can use [Tints](https://www.sketch.com/docs/styling/#tints) for that purpose since this plugin also support them ;)

**Comment by eddiesigner** [comment]
I will close this issue for now, please feel free to reopen it if needed.
